### ISSUE TITLE
Investigate why Tendermint disk storage keeps growing over time

### ISSUE THREAD

**Issue by adizere** [informalsystems/interchain#1]
Mircea:

>  Pruning doesn’t work. Osmosis node grows by 8GB per day with `prune=everything`, and all the available pruning options.

Greg:

> Run a chain with KV store, send transactions. Most likely an SDK issue.
Use tm-load-test against KV-store-backed network.
This would help eliminate Tendermint as a culprit.

Thane, Adi:

> AS and TT will give it a try to do this.
If it proves to be a SDK issue, we’ll be blocked.
TT can help facilitate debugging, and would need someone from the team to fix, capture in an issue, shepherd.

**Comment by jmalicevic** [comment]
I am looking at storage workloads for Tendermint and came back to this thread. While the `tx_index.db` relative growth rate is not very large, it seems to me that the overall % of storage taken by it is. I will double check this in the code (took a quick look now) but, if we prune blocks, we do not seem to prune the index. The index stores the following:
- `txindex` - the transaction hash of every transaction + for every height all transaction hashes + for every attribute of every event within a transaction - it's attributes (attribute key, value, height, index flag).
- `blockindex` - 1 int64 per height + per event attribute 1 string containing attribute key, value, height)

Note that the tendermint kvstore application does not generate block events. The indexer patch for 0.37.1 enables event generation if a flag is set. 

Also, I understand that this itself may not be related to the problem of why compaction is not working but I think it relates to the discussion here.

**Comment by ancazamfir** [comment]
thanks @jmalicevic! I think the issue title might be wrong. imo we are trying to figure out why we cannot have relatively constant disk usage over time. A good product should be able to run for a long time without running out of memory. But what we see:
- leveldb compaction not working properly
- `tx_index.db` pruning doesn't happen (as you point out)
- for all `application.db`, `state.db`, `blockchain.db` and `tx_index.db`, single state size seems to grow over time.

On the last point, I did some gaia tests with no transactions (empty blocks) and used 100 size pruning window for both application state and blocks. 
One would expect that the disk space of states `[H, H+100)` to stay relatively constant as H increases. But this is what we see:
- `application.db` and `tx_index.db` grow at higher speed and hard to blame it all on the compaction issues
  - for `tx_index.db` the growth rate is in fact pretty large and overtime it reaches the size of `application.db` so I think it's important to fix this if possible.
  - `application.db` (with pruning seemingly working) grows at a rate that is not justified by leveldb compaction issues.
- `blockchain.db` and `state.db` increase rate is smaller but still a concern; it could be justified by leveldb inefficiencies. 

@thanethomson brought up the fact that a state attribute might naturally grow in size over higher heights. `height` is one example and therefore it is inevitable to see some state size increase over time.

**Comment by adizere** [comment]
~~Fixed~~ Investigation continues in CometBFT

- https://github.com/cometbft/cometbft/issues/169
- https://github.com/cometbft/cometbft/issues/44
- https://github.com/cometbft/cometbft/issues/48
- https://github.com/cometbft/cometbft/issues/1041
